uploads = []
generated = []

[[outputs]]
id = "2hZbv4yN02dzCqACiSn77"
uri = "file://DEPLOYMENT.md"
type = "text"
title = "ProposalForge Deployment Guide"

[[outputs]]
id = "2RfIQtgnYRdjt9WuoK_-J"
uri = "file://README.md"
type = "text"
title = "ProposalForge README"

[[outputs]]
id = "rLFwrYFnsAELJSVILUmRG"
uri = "file://GITHUB_SETUP.md"
type = "text"
title = "GitHub Push Guide (Step-by-Step)"
